### ISSUE TITLE
Batching only first element

### ISSUE THREAD

**Issue by vinid** [vlukiyanov/pt-avitm#29]
Hi!

I was looking at the code and found you are reassigning the variable `batch` here:

https://github.com/vlukiyanov/pt-avitm/blob/fa96afb5c4a3afa14f6de3d3d3ad2f3d89edd7d1/ptavitm/model.py#L81

is this intentional? 

Thanks a lot! :)

**Comment by vlukiyanov** [comment]
I believe batch here is a 1-tuple (or maybe 1 element list), so this is merely picking out the Tensor object. See tests/test_model.py if you can see something wrong would be helpful :)
