### ISSUE TITLE
Issue in running the code

### ISSUE THREAD

**Issue by MalaMahadevu** [vlukiyanov/pt-avitm#34]
When I run the file 20news.py file, im gettting the below error, although i have not changed the path of the ptavitm definition. 

Error: 
 File "c:\Users\MALA\pt-avitm-master\examples\20news\20news.py", line 15, in <module>
    from ptavitm.model import train
ModuleNotFoundError: No module named 'ptavitm'

**Comment by vlukiyanov** [comment]
I think you need to install the package, the paths isn't enough. See setup.py and README.md in the repo.
